### ISSUE TITLE
검색창 선택할 때, 커서 보이게 해줬으면

### ISSUE THREAD

**Issue by didi027** [pooi/SubwayAlerter#4]
![img_5676](https://cloud.githubusercontent.com/assets/18673145/15268707/cc0839a0-1a22-11e6-89c7-c5115f403012.PNG)

첨부된 사진과 같이 
검색하기 위해서 창을 선택했을때,
키보드는 활성화 되지만, 커서가 보이지 않습니다.

사용자의 오해가 없도록 커서가 보이면 좋겠습니다.

**Comment by pooi** [comment]
검색창의 전체적인 글자 색 변경 밑 닫기 버튼 글자 색 변경 완료
